import dayjs from 'dayjs';
export const spaRoot = window['getOpenmrsSpaBase'];
export const basePath = '/outpatient';
export const spaBasePath = `${window.spaBase}/home`;
export const omrsDateFormat = 'YYYY-MM-DDTHH:mm:ss.SSSZZ';
export const startOfDay = dayjs(new Date().setUTCHours(0, 0, 0, 0)).format(omrsDateFormat);
export const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
export const PRIVILEGE_RECEPTION_METRIC = '';
export const PRIVILIGE_TRIAGE_METRIC = '';
export const PRIVILEGE_CLINICIAN_METRIC = '';
export const PRIVILEGE_RECEPTION_QUEUE_LIST = '';
export const PRIVILEGE_TRIAGE_QUEUE_LIST = '';
export const PRIVILEGE_CLINICIAN_QUEUE_LIST = '';
