export interface systemInfo {
  'SystemInfo.title.moduleInformation': SystemInfoTitleModuleInformation;
}

export interface SystemInfoTitleModuleInformation {
  'SystemInfo.Module.repositoryPath': string;
  'Order Templates': string;
  'Database Backup Module': string;
  'ID Generation': string;
  'Allergy UI Module': string;
  'EMR API Module': string;
  'Patient Queueing': string;
  'HTML Form Entry UI Framework Integration Module': string;
  'App Framework Module': string;
  'Reporting REST': string;
  'Reference Metadata Module': string;
  UgandaemrSync: string;
  'App UI Module': string;
  'Metadata Deploy': string;
  'Reporting Compatibility': string;
  'Bed Management Module': string;
  'O3 Forms': string;
  'HTML Widgets': string;
  'Address Hierarchy': string;
  'Data Entry Statistics': string;
  'Registration Core Module': string;
  Attachments: string;
  'Core Apps Module': string;
  'Bahmni Appointment Scheduling': string;
  FHIR2: string;
  'Appointment Scheduling UI Module': string;
  'Open Web Apps Module': string;
  'HTML Form Entry': string;
  'Reporting UI Module': string;
  'Cohort Module': string;
  'UgandaEMR FingerPrint Module': string;
  'Open Concept Lab Module': string;
  'Form Entry App Module': string;
  Reporting: string;
  'Metadata Sharing': string;
  'AtomFeed Module': string;
  'Registration App Module': string;
  'Metadata Mapping': string;
  'Patient Flags Module': string;
  'Admin UI Module': string;
  'Reference Application Module': string;
  'OpenMRS UI Framework': string;
  XForms: string;
  'Data Integrity Module': string;
  'Single Page Application': string;
  'Serialization Xstream': string;
  'Event Module': string;
  'Stock Management': string;
  'Provider Management Module': string;
  UgandaEMR: string;
  Calculation: string;
  'UI Commons Module': string;
  'Rest Web Services OMOD': string;
  'Legacy UI Module': string;
  'UgandaEMR Reports Module': string;
  'Data Exchange Module': string;
  'UI Library Module': string;
}
